//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vm.Aspects.Security.Cryptography.Ciphers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vm.Aspects.Security.Cryptography.Ciphers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument..
        /// </summary>
        internal static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length of the argument..
        /// </summary>
        internal static string InvalidArgumentLength {
            get {
                return ResourceManager.GetString("InvalidArgumentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encrypted value is not a valid array..
        /// </summary>
        internal static string InvalidEncryptedArray {
            get {
                return ResourceManager.GetString("InvalidEncryptedArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid encrypted value..
        /// </summary>
        internal static string InvalidEncryptedValue {
            get {
                return ResourceManager.GetString("InvalidEncryptedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hash..
        /// </summary>
        internal static string InvalidHash {
            get {
                return ResourceManager.GetString("InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input data does not represent a valid crypto package: could not read the .
        /// </summary>
        internal static string InvalidInputData {
            get {
                return ResourceManager.GetString("InvalidInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected number of bytes read from the data stream..
        /// </summary>
        internal static string InvalidNumberOfBytes {
            get {
                return ResourceManager.GetString("InvalidNumberOfBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument cannot be null, empty string or consist of white space characters only..
        /// </summary>
        internal static string NullOrEmptyArgument {
            get {
                return ResourceManager.GetString("NullOrEmptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input stream does not seem to be produced with a compatible cipher..
        /// </summary>
        internal static string StreamNotCompatible {
            get {
                return ResourceManager.GetString("StreamNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read from the stream..
        /// </summary>
        internal static string StreamNotReadable {
            get {
                return ResourceManager.GetString("StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot seek the stream..
        /// </summary>
        internal static string StreamNotSeekable {
            get {
                return ResourceManager.GetString("StreamNotSeekable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to the stream..
        /// </summary>
        internal static string StreamNotWritable {
            get {
                return ResourceManager.GetString("StreamNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The symmetric key is not initialized..
        /// </summary>
        internal static string UninitializedSymmetricKey {
            get {
                return ResourceManager.GetString("UninitializedSymmetricKey", resourceCulture);
            }
        }
    }
}
