//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vm.Aspects.Diagnostics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vm.Aspects.Diagnostics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Note: The caller does not have the permission to use reflection. Therefore System.Object.ToString() on the object has been dumped instead.).
        /// </summary>
        internal static string CallerDoesNotHavePermissionFormat {
            get {
                return ResourceManager.GetString("CallerDoesNotHavePermissionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static .
        /// </summary>
        internal static string ClassMethodDesignator {
            get {
                return ResourceManager.GetString("ClassMethodDesignator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}[{3}].
        /// </summary>
        internal static string CollectionCountFormat {
            get {
                return ResourceManager.GetString("CollectionCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Could not find a public, static, method {0}, with return type of System.String, with a single parameter of type {1} in the class {2}..
        /// </summary>
        internal static string CouldNotFindCustomDumpers {
            get {
                return ResourceManager.GetString("CouldNotFindCustomDumpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#-like expression text:.
        /// </summary>
        internal static string CSharpDumpLabelFormat {
            get {
                return ResourceManager.GetString("CSharpDumpLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (see above).
        /// </summary>
        internal static string CyclicalReferenceDesignator {
            get {
                return ResourceManager.GetString("CyclicalReferenceDesignator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4}{0}.{3}.
        /// </summary>
        internal static string DelegateDumpFormat {
            get {
                return ResourceManager.GetString("DelegateDumpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        internal static string DictionaryBegin {
            get {
                return ResourceManager.GetString("DictionaryBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string DictionaryEnd {
            get {
                return ResourceManager.GetString("DictionaryEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        internal static string DictionaryKeyBegin {
            get {
                return ResourceManager.GetString("DictionaryKeyBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ] = .
        /// </summary>
        internal static string DictionaryKeyEnd {
            get {
                return ResourceManager.GetString("DictionaryKeyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...object dump reached the maximum depth level. Use the DumpAttribute.MaxDepth to increase the depth level if needed..
        /// </summary>
        internal static string DumpReachedMaxDepth {
            get {
                return ResourceManager.GetString("DumpReachedMaxDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string Ellipsis {
            get {
                return ResourceManager.GetString("Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{3}.
        /// </summary>
        internal static string EnumDumpFormat {
            get {
                return ResourceManager.GetString("EnumDumpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3}.
        /// </summary>
        internal static string EnumFlagDumpFormat {
            get {
                return ResourceManager.GetString("EnumFlagDumpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (.
        /// </summary>
        internal static string EnumFlagsDumpBeginFormat {
            get {
                return ResourceManager.GetString("EnumFlagsDumpBeginFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string EnumFlagsDumpEndFormat {
            get {
                return ResourceManager.GetString("EnumFlagsDumpEndFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | .
        /// </summary>
        internal static string EnumFlagsSeparator {
            get {
                return ResourceManager.GetString("EnumFlagsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string GenericParamFormat {
            get {
                return ResourceManager.GetString("GenericParamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string GenericParamListBegin {
            get {
                return ResourceManager.GetString("GenericParamListBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string GenericParamListEnd {
            get {
                return ResourceManager.GetString("GenericParamListEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string GenericParamSeparator {
            get {
                return ResourceManager.GetString("GenericParamSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        internal static string IndexerEnd {
            get {
                return ResourceManager.GetString("IndexerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string IndexerIndexDumpFormat {
            get {
                return ResourceManager.GetString("IndexerIndexDumpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this[.
        /// </summary>
        internal static string IndexerStart {
            get {
                return ResourceManager.GetString("IndexerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InstanceMethodDesignator {
            get {
                return ResourceManager.GetString("InstanceMethodDesignator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ******.
        /// </summary>
        internal static string MaskInLogs {
            get {
                return ResourceManager.GetString("MaskInLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...
        ///The dump exceeded the maximum length of {0} characters. Either increase the value of the argument maxDumpLength of the constructor of the ObjectTextDumper class, or suppress the dump of some types and properties using DumpAttribute-s and metadata..
        /// </summary>
        internal static string MaxLengthExceeded {
            get {
                return ResourceManager.GetString("MaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}): .
        /// </summary>
        internal static string MemberInfoMemberTypeDumpFormat {
            get {
                return ResourceManager.GetString("MemberInfoMemberTypeDumpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {3}.{6}.
        /// </summary>
        internal static string MethodInfoDumpFormat {
            get {
                return ResourceManager.GetString("MethodInfoDumpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {3}.
        /// </summary>
        internal static string MethodParameterFormat {
            get {
                return ResourceManager.GetString("MethodParameterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string MethodParameterListBegin {
            get {
                return ResourceManager.GetString("MethodParameterListBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string MethodParameterListEnd {
            get {
                return ResourceManager.GetString("MethodParameterListEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string ParametersSeparator {
            get {
                return ResourceManager.GetString("ParametersSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  { .
        /// </summary>
        internal static string PropertyBegin {
            get {
                return ResourceManager.GetString("PropertyBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  }.
        /// </summary>
        internal static string PropertyEnd {
            get {
                return ResourceManager.GetString("PropertyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get;.
        /// </summary>
        internal static string PropertyGetter {
            get {
                return ResourceManager.GetString("PropertyGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-24} = .
        /// </summary>
        internal static string PropertyLabelFormat {
            get {
                return ResourceManager.GetString("PropertyLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set;.
        /// </summary>
        internal static string PropertySetter {
            get {
                return ResourceManager.GetString("PropertySetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System(\..+)?.
        /// </summary>
        internal static string RegexSystemNamespace {
            get {
                return ResourceManager.GetString("RegexSystemNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... dumped the first {0}/{1} elements..
        /// </summary>
        internal static string SequenceDumpTruncatedFormat {
            get {
                return ResourceManager.GetString("SequenceDumpTruncatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string SequenceParamListBegin {
            get {
                return ResourceManager.GetString("SequenceParamListBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;[{0}]: .
        /// </summary>
        internal static string SequenceParamListEnd {
            get {
                return ResourceManager.GetString("SequenceParamListEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({2}).
        /// </summary>
        internal static string SequenceTypeFormat {
            get {
                return ResourceManager.GetString("SequenceTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}[{1}]: .
        /// </summary>
        internal static string SequenceTypeNameFormat {
            get {
                return ResourceManager.GetString("SequenceTypeNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;null&gt;.
        /// </summary>
        internal static string StringNull {
            get {
                return ResourceManager.GetString("StringNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        internal static string StringSingleIndent {
            get {
                return ResourceManager.GetString("StringSingleIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknown&gt;.
        /// </summary>
        internal static string StringUnknown {
            get {
                return ResourceManager.GetString("StringUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({2}):.
        /// </summary>
        internal static string TypeDumpFormat {
            get {
                return ResourceManager.GetString("TypeDumpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}.
        /// </summary>
        internal static string TypeInfoFormat {
            get {
                return ResourceManager.GetString("TypeInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ValueFormat {
            get {
                return ResourceManager.GetString("ValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToString().
        /// </summary>
        internal static string ValueFormatToString {
            get {
                return ResourceManager.GetString("ValueFormatToString", resourceCulture);
            }
        }
    }
}
