//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vm.Aspects.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vm.Aspects.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target value is from the specified enumeration&apos;s set of values..
        /// </summary>
        internal static string ExFromEnumDomain {
            get {
                return ResourceManager.GetString("ExFromEnumDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not negative..
        /// </summary>
        internal static string ExNegatedNonnegativeValidation {
            get {
                return ResourceManager.GetString("ExNegatedNonnegativeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is negative..
        /// </summary>
        internal static string ExNonnegativeValidation {
            get {
                return ResourceManager.GetString("ExNonnegativeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type does not implement IComparable..
        /// </summary>
        internal static string ExNotComparable {
            get {
                return ResourceManager.GetString("ExNotComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target value is not from the enumeration type&apos;s set of values..
        /// </summary>
        internal static string ExNotFromEnumDomain {
            get {
                return ResourceManager.GetString("ExNotFromEnumDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the target element is not nullable enumeration type..
        /// </summary>
        internal static string ExNotNullableEnumType {
            get {
                return ResourceManager.GetString("ExNotNullableEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target string is neither null, nor empty, nor white space character(s) only..
        /// </summary>
        internal static string ExNotNullOrEmptyString {
            get {
                return ResourceManager.GetString("ExNotNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target type cannot be tested for being non-negative..
        /// </summary>
        internal static string ExNotSignedNumber {
            get {
                return ResourceManager.GetString("ExNotSignedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the target element is not System.String..
        /// </summary>
        internal static string ExNotStringType {
            get {
                return ResourceManager.GetString("ExNotStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target string does not represent a valid root URL (top and domain level parts are optional, e.g. Experian.com is missing).
        /// </summary>
        internal static string ExNotValidUrl {
            get {
                return ResourceManager.GetString("ExNotValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validated string does not represent a well-formed document, or valid XML document, or the name of the document root element does not match the specified name..
        /// </summary>
        internal static string ExNotValidXmlString {
            get {
                return ResourceManager.GetString("ExNotValidXmlString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target string is either null, empty or white space character(s) only..
        /// </summary>
        internal static string ExNullOrEmptyString {
            get {
                return ResourceManager.GetString("ExNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validated string is null, or empty, or consists of white-space characters only and does not represent a valid XML document..
        /// </summary>
        internal static string ExNullXmlDocument {
            get {
                return ResourceManager.GetString("ExNullXmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the root element of the XML ({0}) does not match the specified root name ({1})..
        /// </summary>
        internal static string ExRootElementNotMatching {
            get {
                return ResourceManager.GetString("ExRootElementNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target string represents a valid root URL (the top and domain level parts are optional, e.g. vm.com is missing).
        /// </summary>
        internal static string ExValidUrl {
            get {
                return ResourceManager.GetString("ExValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validated string represents a well-formed and valid XML document; and the name of the document root element matches the specified name..
        /// </summary>
        internal static string ExValidXmlString {
            get {
                return ResourceManager.GetString("ExValidXmlString", resourceCulture);
            }
        }
    }
}
