//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vm.Aspects.Security.Cryptography.Ciphers.Utilities.FileCrypt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vm.Aspects.Security.Cryptography.Ciphers.Utilities.FileCrypt.Properties.Resources" +
                            "", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the specified certificate..
        /// </summary>
        internal static string CertNotFound {
            get {
                return ResourceManager.GetString("CertNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destination.clear.txt.
        /// </summary>
        internal static string DestinationClearTxt {
            get {
                return ResourceManager.GetString("DestinationClearTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destination.encrypted.bin.
        /// </summary>
        internal static string DestinationEncryptedBin {
            get {
                return ResourceManager.GetString("DestinationEncryptedBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destination.encrypted.txt.
        /// </summary>
        internal static string DestinationEncryptedTxt {
            get {
                return ResourceManager.GetString("DestinationEncryptedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination file already exists.
        /// </summary>
        internal static string DestinationFileAlreadyExists {
            get {
                return ResourceManager.GetString("DestinationFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt and Base64 decode the source file into the destination file using the certificate specified by the subject. If the destination file already exists - overwrite it..
        /// </summary>
        internal static string HelpTextDecryptWithSubject {
            get {
                return ResourceManager.GetString("HelpTextDecryptWithSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt the source file into the destination file using the certificate specified by the thumbprint..
        /// </summary>
        internal static string HelpTextDecryptWithThumbprint {
            get {
                return ResourceManager.GetString("HelpTextDecryptWithThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt and Base64 encode the source file into the destination file using the certificate specified by the subject. If the destination file already exists - overwrite it..
        /// </summary>
        internal static string HelpTextEncryptWithSubject {
            get {
                return ResourceManager.GetString("HelpTextEncryptWithSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt the source file into the destination file using the certificate specified by the thumbprint..
        /// </summary>
        internal static string HelpTextEncryptWithThumbprint {
            get {
                return ResourceManager.GetString("HelpTextEncryptWithThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid thumbprint..
        /// </summary>
        internal static string InvalidThumbprint {
            get {
                return ResourceManager.GetString("InvalidThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the certificate&apos;s thumbprint or its subject must be specified..
        /// </summary>
        internal static string MissingCertificate {
            get {
                return ResourceManager.GetString("MissingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination file already exists. Do you want to overwrite it? [Y/N]: .
        /// </summary>
        internal static string OverwriteDestinationFile {
            get {
                return ResourceManager.GetString("OverwriteDestinationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to finish....
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Encryption.
        /// </summary>
        internal static string SampleSubject {
            get {
                return ResourceManager.GetString("SampleSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31 89 82 59 8e 4a c1 43 df c9 58 96 a8 f7 2b f0 8c 5d f9 f4.
        /// </summary>
        internal static string SampleThumbprint {
            get {
                return ResourceManager.GetString("SampleThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 318982598e4ac143dfc95896a8f72bf08c5df9f4.
        /// </summary>
        internal static string SampleThumbprintDashes {
            get {
                return ResourceManager.GetString("SampleThumbprintDashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source.clear.txt.
        /// </summary>
        internal static string SourceClearText {
            get {
                return ResourceManager.GetString("SourceClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source.encrypted.bin.
        /// </summary>
        internal static string SourceEncryptedBin {
            get {
                return ResourceManager.GetString("SourceEncryptedBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source.encrypted.txt.
        /// </summary>
        internal static string SourceEncryptedTxt {
            get {
                return ResourceManager.GetString("SourceEncryptedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified source file was not found..
        /// </summary>
        internal static string SourceFileNotFound {
            get {
                return ResourceManager.GetString("SourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The command line options -thumbprint and -subject are mutually exclusive. Use only one of them.&quot;.
        /// </summary>
        internal static string SpecifiedThumbprintAndSubject {
            get {
                return ResourceManager.GetString("SpecifiedThumbprintAndSubject", resourceCulture);
            }
        }
    }
}
